### ISSUE TITLE
Create tree from array of ArrayAccess objects

### ISSUE THREAD

**Issue by cronfy** [BlueM/Tree#18]
Looks like currenty a tree can only be built from array of arrays:

```
    protected function createNode($id, $parent, array $properties): Node
    {
        return new Node($id, $parent, $properties);
    }
```

It would be great if tree could be created from array of `ArrayAccess` objects.

Personally I use my own tree implementation. But now I want to switch to something modern and community driven.

I looked at `nicmart/tree`, but looks like it is not maintained. 

This projects seems to be maintained and updating to new PHP versions, I would like to use it, but lack of described functionality prevents me from it :(

I always create trees from array of objects (just looked over my last projects - I never build a tree from array of arrays).

**Comment by BlueM** [comment]
The problem with `ArrayAccess` is that it is not iterable, and therefore the code cannot simply get the properties / values to be passed to the `Node` constructor. (Dropping the `array` typehint and therefore also allow `ArrayAccess` – or something else – would IMHO not help much, as the `Node` class still would need a way to figure out which properties to use.)

But a possible alternate solution would be to make your objects implement `\Traversable` (or a concrete interface implementing `\Traversable`, such as `\Iterator`), which this library supports. Would that work for your use case?

**Comment by cronfy** [comment]
Sorry, I didn't get why ArrayAccess is not enough.

While it is possible to create tree from:  

```
$data = [
    ['id' => 1, 'parent' => 0, 'title' => 'Node 1'],
    ['id' => 2, 'parent' => 1, 'title' => 'Node 1.1'],
    ['id' => 3, 'parent' => 0, 'title' => 'Node 3'],
    ['id' => 4, 'parent' => 1, 'title' => 'Node 1.2'],
];
$tree = new BlueM\Tree($data);
```

I think nothing stops (except that type hint) to create it from:

```
$data = [
    $category1,
    $category2,
    ...
];
$tree = new BlueM\Tree($data);
```

Where `$category...` are ArrayAccess objects having $category['id'] and $category['parent'] access.

I see that later `$properties` are accessed in the `Node` to lowercase keys (but why?) and in `toArray()` method, which IMHO both are parts of some business logic not related to/required in abstract tree.

What do you think?

**Comment by BlueM** [comment]
Your example would theoretically work for `id` and `parent`. But in most cases there is also some “payload” a node has (one or more properties, such as a name, a URL, …). The tree code does not know in advance which properties to expect, but it determines the properties (which need not even be identical for all nodes) from the input data. And it’s this step in the processing where `ArrayAccess` is insufficient, as you can’t get all “keys” from the array-like object (in your example: `$category1`, `$category2`).

If, on the other hand, `$category1` and `$category2` would implement `\Traversable`, your 2nd example would work.

**Comment by cronfy** [comment]
I do not get why it is assumed that one would inevitably want to call `$node->get('propertyName')` or `$node->getPropertyName()`. It is good with arrays, but if I know that tree is built from objects, I would call something like `$object = $node->getValue()` to get the object and then work with it. In other words, if tree is built from objects, methods like `__call()`, `__get()` or `get()` just would not be used.

**Comment by BlueM** [comment]
I begin to understand. What you’re describing is of course a feasible approach, but in my opinion, it doesn’t fit well in how this library works / what it offers. You mention several methods which would not be used – but they _could_ be used (simply because they are present in the `Node` class). In other words: the library would need to be used differently in your use case, and the client would have to be aware of this. (Compare this to constructing the tree from `Traversable` instances: in this case, the library is used exactly like it is used when constructed from an array.)
Moreover, other things like serialization to JSON (same applies to string serializaton of the whole tree or a node) would not work, as the internals of the object is opaque to the library. Which could of course mitigated by requiring each `ArrayAccess` object to also implement `JsonSerializable`, but this would not even allow including a default `jsonSerialize()` implementation.

**Comment by cronfy** [comment]
Ok, thanks for your support and patience. The question can be closed now.
